name = "procura-ai"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Environment variables for Pages
[vars]
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_bmljZS1naG9zdC00My5jbGVyay5hY2NvdW50cy5kZXYk"
NEXT_PUBLIC_API_URL = "https://procura-api.onrender.com/api/v1"
R2_PUBLIC_URL = "https://pub-aldxtesbexbrqlbpnqpq.r2.dev"
KV_CACHE_TTL = "60"

# Bindings for R2
[[r2_buckets]]
binding = "INVOICE_BUCKET"
bucket_name = "procura-invoices"

# Bindings for KV
[[kv_namespaces]]
binding = "CACHE"
id = "fb6b8853d8a74ed1a4b7f03ddbe24728"
